[Connection Interface]
Bridge=1
; 0 = UART
; 1 = SPI
; 2 = I2C
; 3 = RS485
; 4 = CAN

[Files]
APROM=aprom.bin
DataFlash=dflash.bin
; Maximum filename length is 8 characters

[Config Bits]
Config0=0xFFFFFFFF
Config1=0xFFFFFFFF
; Config0-13

[Programming Options]
APROM=1
DataFlash=0
Config=0
ResetAndRun=0
EraseAll=1
; 0 = disabled
; 1 = enabled

[ISP CAN]
DataFlashBaseAddress=0xFFFFFFFF
ConfigBaseSel=0
; 0 = Config Address 0x00300000
; 1 = Config Address 0x0F300000
